"use client";

import { useTranslations } from "next-intl";
import { FeatureCard } from "./FeatureCard";
import { ScrollReveal } from "./ScrollReveal";

const errorDemo = `$ croktile check kernel.co

kernel.co:12:5: error: tiling mismatch
   dma.copy input.chunkat(16, 8, 4) => shared;
            ^~~~~~~~~~~~~~~~~~~~~~~~~
   dimension 2: chunk size 4 does not divide
   input shape[2] = 10
   
kernel.co:18:3: error: shape incompatible
   mma lhs_tile, rhs_tile => output;
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   lhs inner dim (K=64) != rhs inner dim (K=32)

2 errors found. 0 warnings.`;

const runtimeCheck = `// Runtime checks auto-generated by compiler
$ croktile run kernel.co --runtime-checks

[CHECK] Verifying tensor shapes at entry...
[CHECK] lhs: [128, 256] ✓
[CHECK] rhs: [256, 512] ✓
[CHECK] Tiling factors valid for all dimensions ✓
[CHECK] Shared memory allocation: 32KB / 48KB ✓
[PASS] All 4 runtime checks passed.`;

export function FeatureSafety() {
  const t = useTranslations("features.safety");

  const points = [t("point1"), t("point2"), t("point3")];

  return (
    <FeatureCard
      icon={
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
        </svg>
      }
      title={t("title")}
      subtitle={t("subtitle")}
      description={t("description")}
      reversed
    >
      <div className="space-y-6">
        <div className="space-y-2">
          {points.map((point, i) => (
            <div key={i} className="flex items-start gap-2 text-sm">
              <svg className="w-5 h-5 text-mint-500 shrink-0 mt-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
              </svg>
              <span className="text-[var(--muted-foreground)]">{point}</span>
            </div>
          ))}
        </div>

        <ScrollReveal delay={0.2}>
          <div className="rounded-xl border border-red-500/30 bg-red-500/5 overflow-hidden">
            <div className="flex items-center gap-2 px-4 py-2 border-b border-red-500/20">
              <svg className="w-4 h-4 text-red-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="10" />
                <line x1="15" y1="9" x2="9" y2="15" />
                <line x1="9" y1="9" x2="15" y2="15" />
              </svg>
              <span className="text-xs font-medium text-red-500">
                Compile-time errors caught
              </span>
            </div>
            <div className="p-4 font-mono text-xs overflow-x-auto">
              <pre className="text-[var(--foreground)]"><code>{errorDemo}</code></pre>
            </div>
          </div>
        </ScrollReveal>

        <ScrollReveal delay={0.3}>
          <div className="rounded-xl border border-mint-500/30 bg-mint-500/5 overflow-hidden">
            <div className="flex items-center gap-2 px-4 py-2 border-b border-mint-500/20">
              <svg className="w-4 h-4 text-mint-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M20 6L9 17l-5-5" />
              </svg>
              <span className="text-xs font-medium text-mint-600 dark:text-mint-400">
                Runtime checks passed
              </span>
            </div>
            <div className="p-4 font-mono text-xs overflow-x-auto">
              <pre className="text-[var(--foreground)]"><code>{runtimeCheck}</code></pre>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </FeatureCard>
  );
}
